#[cfg(any(feature = "postgres", feature = "mysql", feature = "sqlite"))]
use migration::TABLES;
#[cfg(any(feature = "postgres", feature = "mysql", feature = "sqlite"))]
use sea_orm_codegen::{DateTimeCrate, EntityTransformer, EntityWriterContext, WithSerde};
#[cfg(any(feature = "postgres", feature = "mysql", feature = "sqlite"))]
use std::process::{Command, Stdio};
use std::{env, fs::File, io::Write};

/// Create an alias for `#[cfg]` attributes to use
macro_rules! cfg_aliases {
    ($($alias:tt = $config:meta),* $(,)*) => {
        $(
            if cfg!($config) {
                println!("cargo:rustc-cfg={}", stringify!($alias));
            }
        )*
    };
}

/// All features that should not be shown in the build_data.rs file
const HIDDEN_FEATURES: [&str; 1] = ["default"];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // figure out enabled features
    let features: Vec<_> = env::vars()
        .map(|(k, _)| k)
        .filter(|k| k.starts_with("CARGO_FEATURE_"))
        .map(|k| {
            k.split("CARGO_FEATURE_")
                .last()
                .expect("there should be something after CARGO_FEATURE_")
                .to_lowercase()
        })
        .filter(|k| !HIDDEN_FEATURES.contains(&k.as_str()))
        .collect();

    // save all of this information in in build_data.rs
    let mut file = File::create("src/build_data.rs")?;
    file.write_all(
        format!(
            r#"// This file is generated by build.rs, do not edit it manually
pub const FEATURES: [&str; {}] = [{}];"#,
            features.len(),
            features
                .iter()
                .map(|f| format!("\"{}\"", f))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .as_bytes(),
    )?;

    // generate entity files
    #[cfg(any(feature = "postgres", feature = "mysql", feature = "sqlite"))]
    let files = EntityTransformer::transform(TABLES.clone())?
        .generate(&EntityWriterContext::new(
            false,
            WithSerde::None,
            false,
            DateTimeCrate::Time,
            Some("public".into()),
            false,
            false,
            false,
            vec![],
            vec![],
        ))
        .files;

    #[cfg(any(feature = "postgres", feature = "mysql", feature = "sqlite"))]
    for out_file in files {
        let mut file = File::create(format!("src/db/entity/{}", out_file.name))?;

        let contents = if out_file.name != "mod.rs" {
            // pass the file to rustfmt
            let proc = Command::new("rustfmt")
                .args(["/dev/fd/0", "--emit", "stdout", "--edition", "2021"])
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .spawn()?;

            proc.stdin
                .as_ref()
                .expect("it always exists")
                .write_all(out_file.content.as_bytes())?;

            let output = proc.wait_with_output()?;
            let output = String::from_utf8_lossy(output.stdout.as_slice());
            let pos = output.find("\n\n").unwrap() + 2;

            output[pos..].to_string()
        } else {
            out_file.content.replace(" ;", ";")
        };

        file.write_all(contents.as_bytes())?;
    }

    cfg_aliases! {
        // general

        // is the tui enabled?
        tui = feature = "tui",
        // is the bot johnny?
        johnny = feature = "johnny",
        // should the logger be verbose?
        verbose = feature = "verbose",

        // database drivers

        // does the bot use sqlite?
        sqlite = feature = "sqlite",
        // is a single database driver enabled?
        db = any(feature = "postgres", feature = "mysql", feature = "sqlite"),
        // are multiple of the database drivers enabled?
        multiple_db = any(all(feature = "postgres", feature = "mysql"), all(feature = "mysql", feature = "sqlite"), all(feature = "postgres", feature = "sqlite"), all(feature = "postgres", feature = "mysql", feature = "sqlite")),

        // modules

        // is autorole enabled?
        autorole = feature = "autorole",

        // are pride commands enabled?
        pride = feature = "pride",

        // other

        // is the bot running in a development environment?
        dev = feature = "development",
    }

    Ok(())
}
